Repository RedHatQE/openshift-operator-utilities, pull requests merged in 2024-01, with the labels that each got.

#8 Point to main
  poetry.lock
  pyproject.toml
Labels: verified, size/L, branch-main

#11 Revert "Point to main"
  poetry.lock
  pyproject.toml
Labels: verified, size/L, branch-main

#13 Update poetry, set kubernetes to >28.0.0
  poetry.lock
  pyproject.toml
Labels: verified, size/S, branch-main, approved-dbasunag

#17 update poetry
  poetry.lock
  pyproject.toml
Labels: verified, size/XS, branch-main
